# Code snippets 1: 23/11/24
* 1.Import of mofules, 2. indexing and slicing, 3. timing

## Q1: Beginner level
### Many similar ways to import a function(s) and modules.
* Use dir() to list all methods you have currently available in your so-called namespace

In [1]:
# lists your built-in namespace, which is available on the python start-up
dir(__builtins__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BaseExceptionGroup',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EncodingWarning',
 'EnvironmentError',
 'Exception',
 'ExceptionGroup',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'Runti

In [2]:
# imports all methods and submodules from numpy, generally not a good idea
from numpy import *

# advanced: specifying seed makes your random numbers reproducible (good for testing sometimes)
# random.seed(42)
random.rand(5)

array([0.23972956, 0.81945319, 0.44074331, 0.30019767, 0.28515725])

In [3]:
# imports all methods from numpy.random module
from numpy.random import *

# seed(42)
rand(5)

array([0.88532479, 0.71739011, 0.71557461, 0.64188718, 0.60424882])

In [4]:
# imports one specific function
from numpy.random import rand

# seed(42)
rand(5)

array([0.04648513, 0.52385961, 0.27677908, 0.23075824, 0.87020471])

In [5]:
# typical way to import numpy, you will then always refer to to numpy by np.
# This way you have access to all functions, but the need to refer with full reference, ie np.random.rand(), it is explicit which function you are using
import numpy as np

np.random.rand(5)

array([0.09463212, 0.84088951, 0.0148531 , 0.02652583, 0.2219438 ])

In [6]:
# dir()

In [6]:
# do not redefine your built-in functions
# after running this you cannot use print() built-in function
# advanced question: can you still access the print anyways? Hint: look at the __builtins__
var = 5
print = 'hello'
list = []
str, set

(str, set)

In [10]:
print

'hello'

In [11]:
# If something like this happens, restart your jupyter kernel (kernel -> Restart kernel)
# that cleans all the imports, and variables
# all cells you want to run need to be run again.
print('hello')

TypeError: 'str' object is not callable

In [12]:
# these are rptected words, you cannot use for variable and function names  
help("keywords")


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 



## Q2: Intermediate level
### Array indexing and slicing

In [14]:
import numpy as np

In [15]:
# generate range of numbers (in python we count from 0, always)
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
# reshape makes 1D array 2 dimensional
arr = np.arange(24).reshape(4, 6)

In [28]:
# the same, but I let python to try to assume the second dimension.
# number of elements must match, reshape(5, -1) will not work
arr = np.arange(24).reshape(4, -1)
arr.shape, arr

((4, 6),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]))

In [30]:
arr[0, :]  # or arr[0]

array([0, 1, 2, 3, 4, 5])

In [31]:
arr[5, 4]

IndexError: index 5 is out of bounds for axis 0 with size 4

In [33]:
# index -1 refers to the last element
# : before the index, takes all the elements until the index (indexed position exluded), ie :3 takes elements 0,1,2, but 3 anymore
# : after the index, takes all the elemnets until the end of the array in that dimension. 2: takes elements 2, 3, 4... 
arr[-2:, -3:]

array([[15, 16, 17],
       [21, 22, 23]])

In [34]:
arr[-0]

array([0, 1, 2, 3, 4, 5])

In [35]:
arr[0:2] == arr[:2]  # compares all elements one by one, shapes has to match

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [38]:
# compares if all elements are equal
arr[0:2].all() == arr[:2].all()

True

In [39]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [37]:
# every secon element in the first rom
arr[1, ::2]

array([ 6,  8, 10])

In [40]:
arr[1, :4:2]

array([6, 8])

## Q3: Advanced level
* one module for short snippet code testing is called `timeit`
* other module containing many other time related functions is `time`
* careful with magic %% commands, %% has to be on the first line of the cell (try putting even comment on the first line, and it breaks)
* https://ipython.readthedocs.io/en/stable/interactive/magics.html

In [5]:
%%timeit  # this is specific for jupyter, timing of the cell
for i in range(100):
    i+i

2.63 µs ± 48.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
%%timeit
for i in range(100):
    i*i

3.3 µs ± 31.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
%%timeit
for i in range(100):
    i**i

33.5 µs ± 322 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
# other way to do it
from time import perf_counter

In [8]:
# this runs just once, no statistics
beg = perf_counter()
for i in range(100):
    i**i
end = perf_counter()
print(f'Wall time: {end-beg} s')

Wall time: 0.0011767999967560172 s
